use std::error::Error;
use std::path::Path;

fn main() -> Result<(), Box<dyn Error>> {
    let out_dir = std::env::var("OUT_DIR")?;
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR")?;

    // The specs ship inside the nifi-openapi-gen crate. The helper resolves
    // them relative to nifi-openapi-gen's own manifest dir, which works whether
    // that crate is consumed via path dep (workspace dev build) or pulled from
    // the registry (downstream consumers, `cargo package` verify build).
    let specs_dir = nifi_openapi_gen::specs_dir();
    let specs_dir = specs_dir
        .canonicalize()
        .map_err(|e| format!("Cannot find specs dir {}: {e}", specs_dir.display()))?;

    let config = nifi_openapi_gen::build_api::GenerateConfig::from_cargo_env();

    // Guard against the "no version feature enabled" configuration. This can
    // only happen with --no-default-features and no explicit nifi-x-y-z or
    // `dynamic` feature. Without this guard the build silently produces an
    // empty API surface. The same guard is enforced statically in lib.rs via
    // compile_error!; this build-side check gives an earlier, clearer message.
    if config.versions.is_empty() {
        return Err(
            "No NiFi version feature enabled. Enable one of `nifi-2-6-0`, \
             `nifi-2-7-2`, `nifi-2-8-0`, or the `dynamic` feature in your \
             Cargo.toml."
                .into(),
        );
    }

    // Tell rustc that at least one version feature is active. lib.rs uses
    // `#[cfg(not(has_any_version))]` as a defence-in-depth static guard
    // for code paths that somehow bypass this build script. This flag is
    // not a Cargo feature, so it is invisible to users — there is no way
    // to set it from the outside.
    println!("cargo::rustc-cfg=has_any_version");
    println!("cargo::rustc-check-cfg=cfg(has_any_version)");

    nifi_openapi_gen::build_api::generate_client(&specs_dir, Path::new(&out_dir), &config);

    // Copy hand-written strategy.rs into $OUT_DIR/dynamic/ so the generated
    // lib.rs can mount `pub mod dynamic` pointing to a minimal stub that
    // re-exports `strategy`. The canonical emitter no longer writes dynamic/
    // so we create it here.
    //
    // NOTE: Task 6 (rename dynamic_v2 → dynamic) will move strategy.rs into
    // dynamic_v2/ and eliminate this stub entirely.
    if config.dynamic {
        let strategy_src = Path::new(&manifest_dir).join("src/dynamic/strategy.rs");
        let dynamic_dir = Path::new(&out_dir).join("dynamic");
        std::fs::create_dir_all(&dynamic_dir)
            .map_err(|e| format!("failed to create dynamic stub dir: {e}"))?;
        let strategy_dst = dynamic_dir.join("strategy.rs");
        if strategy_src.exists() {
            std::fs::copy(&strategy_src, &strategy_dst).map_err(|e| {
                format!(
                    "Failed to copy strategy.rs from {} to {}: {e}",
                    strategy_src.display(),
                    strategy_dst.display()
                )
            })?;
        }
        // Write a minimal mod.rs for the dynamic stub. This exposes just enough
        // for hand-written files (builder.rs, pagination.rs) to compile while
        // the legacy dispatch layer is gone and dynamic_v2 hasn't been renamed
        // to `dynamic` yet (Task 6 will do that rename and eliminate this stub).
        //
        // - `strategy` + `VersionResolutionStrategy` re-export: used by builder.rs
        //   and dynamic_v2/client.rs.
        // - `DynamicClient` type alias → `DynamicClientV2`: used by builder.rs
        //   (`build_dynamic`) and pagination.rs (`flow_history_dynamic`).
        // - `traits` re-export via `dynamic_v2`: used by pagination.rs.
        // - `types` re-export via `dynamic_v2`: used by pagination.rs.
        let mod_rs_path = dynamic_dir.join("mod.rs");
        std::fs::write(
            &mod_rs_path,
            "// @generated — do not edit; regenerated by build.rs\n\
             // Minimal stub — Task 6 eliminates this when dynamic_v2 → dynamic.\n\n\
             /// Version resolution strategy for dynamic dispatch.\n\
             pub mod strategy;\n\
             pub use strategy::VersionResolutionStrategy;\n\n\
             /// DetectedVersion re-exported from canonical availability module.\n\
             /// Used by strategy.rs as `super::DetectedVersion`.\n\
             pub use crate::dynamic_v2::availability::DetectedVersion;\n\n\
             /// Alias to the canonical dynamic client (dynamic_v2 until Task 6 renames it).\n\
             pub use crate::dynamic_v2::DynamicClientV2 as DynamicClient;\n\n\
             /// Re-export types from canonical module for backward compat.\n\
             pub mod types {\n\
                 pub use crate::dynamic_v2::types::*;\n\
             }\n\n\
             /// Re-export trait stubs for backward compat.\n\
             pub mod traits {\n\
                 pub use crate::dynamic_v2::api::*;\n\
             }\n",
        )
        .map_err(|e| format!("failed to write dynamic/mod.rs stub: {e}"))?;
    }

    if config.dynamic && config.versions.len() > 1 {
        let dynamic_v2_src_dir = Path::new(&manifest_dir).join("src/dynamic_v2");
        let dynamic_v2_dst_dir = Path::new(&out_dir).join("dynamic_v2");
        std::fs::create_dir_all(&dynamic_v2_dst_dir)
            .map_err(|e| format!("failed to create dynamic_v2 dir: {e}"))?;
        for entry in std::fs::read_dir(&dynamic_v2_src_dir)
            .map_err(|e| format!("failed to read src/dynamic_v2: {e}"))?
        {
            let entry = entry.map_err(|e| format!("read_dir entry: {e}"))?;
            let src = entry.path();
            // Only copy `client.rs`. The hand-written `mod.rs` in src/dynamic_v2/
            // exists only for IDE/rust-analyzer happiness while developers edit
            // `client.rs`; the generated `dynamic_v2/mod.rs` is the real
            // orchestrator and must not be overwritten.
            if src.extension().and_then(|s| s.to_str()) == Some("rs")
                && entry.file_name() != "mod.rs"
            {
                let dst = dynamic_v2_dst_dir.join(entry.file_name());
                std::fs::copy(&src, &dst).map_err(|e| {
                    format!("failed to copy {} to {}: {e}", src.display(), dst.display())
                })?;
            }
        }
        println!("cargo::rerun-if-changed=src/dynamic_v2");
    }

    println!("cargo::rerun-if-changed={}", specs_dir.display());
    println!("cargo::rerun-if-changed=build.rs");
    println!("cargo::rerun-if-changed=src/dynamic/strategy.rs");

    Ok(())
}
