// @generated — do not edit; run `cargo run -p nifi-openapi-gen`

mod access;
pub use access::AccessApiDispatch;
mod authentication;
pub use authentication::AuthenticationApiDispatch;
mod connections;
pub use connections::ConnectionsApiDispatch;
mod controller;
pub use controller::ControllerApiDispatch;
mod controller_services;
pub use controller_services::ControllerServicesApiDispatch;
mod counters;
pub use counters::CountersApiDispatch;
mod datatransfer;
pub use datatransfer::DataTransferApiDispatch;
mod flow;
pub use flow::FlowApiDispatch;
mod flowfilequeues;
pub use flowfilequeues::FlowFileQueuesApiDispatch;
mod funnels;
pub use funnels::FunnelsApiDispatch;
mod inputports;
pub use inputports::InputPortsApiDispatch;
mod labels;
pub use labels::LabelsApiDispatch;
mod outputports;
pub use outputports::OutputPortsApiDispatch;
mod parametercontexts;
pub use parametercontexts::ParameterContextsApiDispatch;
mod parameterproviders;
pub use parameterproviders::ParameterProvidersApiDispatch;
mod policies;
pub use policies::PoliciesApiDispatch;
mod processgroups;
pub use processgroups::ProcessGroupsApiDispatch;
mod processors;
pub use processors::ProcessorsApiDispatch;
mod provenance;
pub use provenance::ProvenanceApiDispatch;
mod provenanceevents;
pub use provenanceevents::ProvenanceEventsApiDispatch;
mod remoteprocessgroups;
pub use remoteprocessgroups::RemoteProcessGroupsApiDispatch;
mod reportingtasks;
pub use reportingtasks::ReportingTasksApiDispatch;
mod resources;
pub use resources::ResourcesApiDispatch;
mod sitetosite;
pub use sitetosite::SiteToSiteApiDispatch;
mod snippets;
pub use snippets::SnippetsApiDispatch;
mod systemdiagnostics;
pub use systemdiagnostics::SystemDiagnosticsApiDispatch;
mod tenants;
pub use tenants::TenantsApiDispatch;
mod versions;
pub use versions::VersionsApiDispatch;
